check pathway length without removing item from set, remove extra print statement
CNERG/trailmap pull request #39
Opened 2021-03-24 17:42 UTC by nuclearkatie

Corrects a few things that were missed in #34 

Removes extra print statement that was in `scripts/main.py`

Finds the longest and shortest pathways without losing one

- Printing the shortest/longest length was popping an item from a set to get the length, which then removes that item from the set. 
- When the list of pathways with longest/shortest length is printed, one item is missing
- Changed to len(next(iter(set_of_pathways()))) which does not remove the item

2021-03-26 11:19 UTC, gonuke requested changes
Just a question about the implementation

2021-03-26 11:19 UTC, gonuke commented on trailmap/pathway_analysis.py
> +    print("\nThe shortest pathway is length " + str(len(next(iter(shortest)))))
Why not just?
```suggestion
    print("\nThe shortest pathway is length " + str(len(shortest[0]))
```

2021-03-29 16:50 UTC, nuclearkatie commented on trailmap/pathway_analysis.py
> +    print("\nThe shortest pathway is length " + str(len(next(iter(shortest)))))
shortest/longest are sets!

2021-03-30 12:47 UTC, gonuke approved these changes
Thanks for the clarification- I should have seen/remembered that.

2021-03-30 12:47 UTC, merged